### ISSUE TITLE
SR — Set RC Servo power timeout

### ISSUE THREAD

**Issue by IxamTsirk** [evil-mad/EggBot#184]
Hi,

I am an absolute beginner and have no experience in coding.
I am just using my few Axi Draws via Inkscape and experienced an annoying problem.
I am using a pen with some extra weights and once the Axi Draw finished the plot the servo switches off after 60 seconds. When the servo switches off, it lowers the pen because the natural resistance of the servo is not strong enough to hold it. If I would start a new plot without lifting the servo up at first, the pen would draw until the servo receives its first command.
I have read in your EBB (EiBotBoard) Command Set that it is possible to change the value to 0 and then the auto-poweroff feature is disabled.
I have absolutely no glue how and where to set that value.
Do you have a ready to install version of the firmware for newer Axi Draws (I bought them about 8 months ago) that already disables the auto-poweroff feature?
I would be very grateful, if anybody could help me! :)

**Comment by oskay** [comment]
You can find the current version of the AxiDraw software at: http://axidraw.com/sw

The servo timeout is set in the AxiDraw configuration file, `axidraw_conf.py`. You can find this location as follows:
A. Open Inkscape
B. From the menu, select **Inkscape > Preferences** (on a Mac) or **Edit > Preferences** (if using Windows)
C. Select System from the list on the left panel of the preferences window.
D. On the right-hand panel is a list of folder locations. Click the "Open" button to the right of the "User extensions" folder location. This will open the extensions folder on your computer.

Open that file in a plain text editor and look for `servo_timeout` in it, set by default to 60000. You can change that how you need to. This value is reset when the AxiDraw resets (loses power or is otherwise rebooted), but should be remembered in a session once it has been set the first time.

Additionally, we have some new servo options coming later this fall (or early 2023) that will provide the possibility of more lifting force and more downforce without added weights.
