### ISSUE TITLE
anti virus trigger

### ISSUE THREAD

**Issue by rhawley88** [evil-mad/EggBot#198]
I just downloaded the zip to update my egg bot and Inkscape, and antivirus triggered on this .exe and none of the others. Sorry wasn't sure the best way to bring this to your attention. I'm only on this page 2 or 3 times a year.

EggBot-master\EggBot-master\EBB_firmware\EBBUpdater\deprecated\EBBUpgraderGUI_v280.exe tried to load a malicious resource detected as Gen:Trojan.Heur.RP.MmW@bihjB!ei and was blocked. Your device is safe.

**Comment by oskay** [comment]
Unfortunately there isn't anything that we can do about these types of detections in general.

A heuristic detection like that means that this is a file that's an .exe, and that an unknown-to-them .exe file could potentially download something from the internet. (In this case, it doesn't.)  For every different malware protection program/app/database, and for every version of every updater and installer that we manage, there's always some chance for random false positives like these.

I've submitted it as a false positive for that particular company, but that's the only thing that we can do to help. Most companies push updates that allow the after we report false positives, but since they rely on fingerprints, they won't be good for future versions. Note for example that I submitted the *current* release not the deprecated one that you mention.

**Comment by rhawley88** [comment]
Thanks yeah I was surprised to see it trigger. I've been downloading from the github for years for my eggbot and never had it trigger before. was more surprised that it only triggered on the one. Figured it was a false positive but wanted it to be brought to your attention. Sorry for taking up your time. Sent from my Galaxy
-------- Original message --------From: Windell Oskay ***@***.***> Date: 4/10/23  12:06 AM  (GMT-05:00) To: evil-mad/EggBot ***@***.***> Cc: rhawley88 ***@***.***>, Manual ***@***.***> Subject: Re: [evil-mad/EggBot] anti virus trigger (Issue #198) 
Unfortunately there isn't anything that we can do about these types of detections in general.
A heuristic detection like that means that this is a file that's an .exe, and that an unknown-to-them .exe file could potentially download something from the internet. (In this case, it doesn't.)  For every different malware protection program/app/database, and for every version of every updater and installer that we manage, there's always some chance for random false positives like these.
I've submitted it as a false positive for that particular company, but that's the only thing that we can do to help. Most companies push updates that allow the after we report false positives, but since they rely on fingerprints, they won't be good for future versions. Note for example that I submitted the current release not the deprecated one that you mention.
