### ISSUE TITLE
Add simple limit switch inputs to EBB for stepper axes

### ISSUE THREAD

**Issue by oskay** [evil-mad/EggBot#4]
Via @EmbeddedMan in https://code.google.com/p/eggbotcode/issues/detail?id=57

"Add new SC commands to allow setting up of two inputs per axis that when tripped will cause the motor not to step any more in that direction. Make each input selectable as to high or low being 'tripped'."

**Comment by pacvis** [comment]
So is this a thing? I'm keen to see it. FYI another reason to have 4 limit sw configurations is for professional systems because they have a "hard" limit switch which halts all motion and disables motor and another limit switch a few mm's away that acts as a proper "home" switch. The hm operation then moves motor to the home switch falls (or rises)...goes past and then reverses the motor and waits until the state changes back. This provides home with hardstop that prevents equipment damage if, (for instance communication is lost or corrupted. Grt feature and not very hard to implement if you just wire it to the low level motor counting routine.

**Comment by EmbeddedMan** [comment]
Agreed that it would be a very good thing to add. Currently this feature is not implemented as of 2.6.2.

**Comment by EmbeddedMan** [comment]
This functionality now exists in the EBF_v3.0.0 branch and will be part of the v3.0.0 EBB firmware release. Please see issue #58 for more information on how the limit switch command is now implemented. I'm going to close this one as a duplicate.
