### ISSUE TITLE
PenDown uses PenUp delay

### ISSUE THREAD

**Issue by ShelMi** [evil-mad/EggBot#41]
Correct me if I'm wrong, but it looks as though a copy-and-paste operation went awry in the following code (check out the delay specified in the last line):
`	def penDown( self ):
		self.virtualPenIsUp = False  # Virtual pen keeps track of state for resuming plotting.
		if (self.bPenIsUp != False):  # Continue only if pen state is up (or unknown)
			if ( not self.resumeMode ) and (not self.bStopped):  # skip if we're resuming or stopped
				self.bPenIsUp = False
				if self.penDownActivatesEngraver:
						self.engraverOn() # will check self.enableEngraver
				ebb_motion.sendPenDown(self.serialPort, self.options.penUpDelay )	`

**Comment by oskay** [comment]
Good catch! I think that I came across this recently, myself. I'm actually planning to replace the whole pen up/down timing with new logic (first implemented for AxiDraw-- https://github.com/evil-mad/axidraw ), that computes the delay times automatically from the servo distance to be travelled + the servo travel speed.  

You can see the logic for it in axidraw.py, in `def penUp` and def `penDown`.  We still have timing adjustment available there, but it's phrased as an additive modification ("extra delay after pen up"), rather than as a total.
