### ISSUE TITLE
EBB Firmware: Add Abort command - to stop long moves

### ISSUE THREAD

**Issue by oskay** [evil-mad/EggBot#8]
Migrated from original report by @EmbeddedMan : https://code.google.com/p/eggbotcode/issues/detail?id=80

"Once we add 3 byte long step and duration parameters for the SM command, and add commands for homing, we start to see some things take very long times (a 3-byte duration in milliseconds is 4.7 hours). If something goes wrong, or you need to bail on a long command, it would be very useful to have an 'abort' command that would allow you to stop a long move or a home operation.

Note that, with the current system of flow-control built into USB, if you send two long SM commands back to back, the abort won't do you any good because it can't be processed until after the second long move is processed. 

However, if you're careful, just send out one long move at a time, then you can abort.

In the future, we can make a more sophisticated flow control method (where there is a longer FIFO of queued moves in the EBB, and the USB interface never blocks) or something like that, and then the abort will have more meaning.

We could also use a digital input as an abort. Right now, the PRG button acts as a 'pause' button, but this is something handled up at the application level (Inkscape) rather than at the EBB level. Having a hardware Estop input might be really nice."

**Comment by bmaranville** [comment]
We're using an EBB on an interactive measurement lab device, and abort would be very useful for us too.  (there is a software stop-all button on the program into which this is integrated - it would be nice if it worked for all the hardware!)

**Comment by EmbeddedMan** [comment]
I don't think this will be hard to add at all. Should we use one of the PortB pins on the EBB as a default "E-Stop" button input on boot? The idea would be that if that input ever got pulled low, any stepper move command would be aborted immediately, and any new SM commands sent to the EBB would in essence be ignore until the input was set back high.

Would that work for you?

**Comment by bmaranville** [comment]
Sorry, I meant that we would like the software abort (rather than the hardware abort.)

**Comment by EmbeddedMan** [comment]
Ahh, that's not something that is easy unfortunately. It will take changes on both the PC side and the EBB side. The EBB side firmware will need to be re-written to use a different flow control method so that you can send a command to the EBB (to abort) even though the EBB has queued up stepper moves waiting. Maybe there's a simple way to do it, but I can't think of one off the top of my head.

One solution is for you to change your PC side software to send lots of short moves (which, when strung together, form long moves). By breaking up everything into really short segments (maybe no more than 100ms moves) you will then only ever have to wait a maximum of 200ms before your 'abort' will take effect. (In this case, the 'abort' would simply be not sending any more move commands.)

**Comment by oskay** [comment]
It would be great for us if (say) B0 acted essentially identically to the PRG button, in the sense that it could be used to attach an *external* button that could pause a plot underway.

**Comment by EmbeddedMan** [comment]
Absolutely. I'll look into it tonight.

**Comment by bmaranville** [comment]
For the software abort, we only have one move ongoing at a time (using "QM" to check if moving before issuing a new move) so there's nothing in the queue ahead of the "abort".  I've realized that sending "EM,0,0" ends the move but it also disables the motor.  I'd prefer an option that stops the move but leaves the motor engaged.

**Comment by EmbeddedMan** [comment]
OK, that's cool. I think in that case (where there are no moves in the
FIFO, and just one executing) it would be pretty easy to add a new "abort"
software command that would simply terminate the current command. I'll take
a look at it tonight too. Good suggestion.

**Comment by EmbeddedMan** [comment]
Oskay- I've confirmed that in the current version of EBB firmware (2.2.6) the functionality you ask for is already there. Port RB0 is already configured as an alternate 'pause' button. RB0 is pulled up internally in the PIC. If you ground RB0, it will consider that a 'press' of the pause button, and the QB command will return "1" just as if the user had pressed the PRG button. That functionality has been there since 2.0.1. I believe.

**Comment by EmbeddedMan** [comment]
bmaranville - I have created EBB v2.2.7, which includes a new command called "ES" for you. (E-Stop). Here is the hex file for v2.2.7 so you can update your EBB : 
(https://github.com/evil-mad/EggBot/raw/master/EBB_firmware/Releases/app/EBF_v227.zip)
And here is the updated documentation for v2.2.7
(http://www.schmalzhaus.com/EBB/EBBCommands.html)

Please try it out, and see if it works for you.

**Comment by EmbeddedMan** [comment]
Sorry - I forgot to upload the new files to my website. The commands and release notes pages have now been updated.

**Comment by bmaranville** [comment]
The EStop command works as advertised!

**Comment by EmbeddedMan** [comment]
Yes!! Great news. So, I think that, for now, this issue can be closed. If,
in the future, we really do want to enable this functionality in a system
where there is a way to stop an EBB even if it's buffer is full and the PC
is trying to push more moves down to it, we can open another issue with
more ideas as to how exactly to do that.
