### ISSUE TITLE
Windows EXE is marked as infected

### ISSUE THREAD

**Issue by ftiex** [evil-mad/EggBot#88]
The eggbot_240a.exe is removed by my Norton virus scanner, as it found a virus or trojan named "WS.Reputation.1". 

Also here http://www.herdprotect.com/eggbot_240a.exe-e794877b5e2ee4a04f5e33994cf46308e8532fe8.aspx 
the file is marked as infected.

**Comment by oskay** [comment]
No, that is **not at all** what happened. 

We have had occasional issues with false positives from various scanning software based on heuristic models such as "very few people use this file."  What you have seen is exactly an example of that -- "WS.Reputation.1" is **not* the name of a virus or trojan, but an indication that the file tripped the "WS.Reputation.1" flag in Norton, meaning that it's a relatively unknown file.  (Why? The total number of EggBot users who use both (1) Windows and (2) this particular flavor type of Norton and (3) this particular version of the EggBot software installer is quite low.)


The additional flags that were triggered on Herdprotect are the same types, with an overall "Inconclusive" label and 4/68 flags. That means that 68 of 68 different malware scanning engines looked at our software, and **all agreed that there was no detection of any known viruses, trojans, malware, or similar things**. Four of the 68 engines said "this file might be suspicious." _64_ of the engines said it's fine.

The reasons that it's pulling those flags on a small minority of the software are (1) it's relatively unknown and (2) it contains another executable program. The executable program is one that is run during installation only, and has the sole function to install the EggBot's USB driver. This general characteristic -- containing another program -- is used by some modern adware programs, which is why you have those four flags there.

The messages on each of those engines confirm this:

* "PUP/Win32.WindowNM" -- "Potentially unwanted program" 
* "Win.Adware.Domaiq-135" -- Thinks it might be adware
* "Artemis" --  McAfee's AI detection for things that look suspicious
* "Suspicious" -- Same thing.

As a workaround, you can either:

(1) Temporarily disable that kind of heuristic detection on your computer while you install the software
https://www.symantec.com/connect/forums/how-disable-wsreputation1-detection

or

(2) Manually install the software without the easy installer.
